name: Build APK Manual
on: 
  workflow_dispatch: # Ini yang bikin ada tombol "Run workflow" manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: android
          
      # Trik supaya gak perlu upload gradlew manual (opsional tapi disarankan)
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Build Debug APK
        run: gradle assembleDebug
        
      - name: Upload APK Hasil Build
        uses: actions/upload-artifact@v4
        with:
          name: Kamera-A16-Redmi
          path: app/build/outputs/apk/debug/app-debug.apk
          
