name: Build Aperture Camera (Sapphiren)

on:
  workflow_dispatch: # Trigger manual sesuai permintaan

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 21 # Android 16 QPR2 standar menggunakan Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant Permission to Gradlew
        run: chmod +x gradlew

      - name: Build APK (Release/Debug)
        run: ./gradlew assembleDebug # Gunakan assembleRelease jika sudah ada keystore

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Aperture-Sapphiren-Android16
          path: app/build/outputs/apk/debug/*.apk
